# Abdelrahman Rezk
# ML & NLP Student

# Web Developer 



# "Binary Classification with multiple of features"
This is a Logistic Regression (Classification) example that explain at basic level how the model work 
with simple data that will create every thing from 0 level and steps of work will be on these function
h(x) predicted value
cost function
gradient descent



In [9]:
import numpy as np
import pandas as pd


In [10]:
X = np.array([
    ["Ahmed", 1, 18, 70],
    ["Hamed",0, 22 ,88],
    ["Mona",0, 38, 91],
    ["Said",1, 21, 65],
    ["Lobna",1, 25, 79]
])
print("###########################################")
print(X.shape)
X

###########################################
(5, 4)


array([['Ahmed', '1', '18', '70'],
       ['Hamed', '0', '22', '88'],
       ['Mona', '0', '38', '91'],
       ['Said', '1', '21', '65'],
       ['Lobna', '1', '25', '79']], dtype='<U5')

In [11]:
y = np.array([
    [1],
    [1],
    [1],
    [0],
    [0]
    
])
print("###########################################")

print(y.shape)
y

###########################################
(5, 1)


array([[1],
       [1],
       [1],
       [0],
       [0]])

# first 
    we should remove the feature name 
    that is will not affect our algorithm with nothing
    actually maybe lead to misleading so we don't care of using the name feature
# second
    we will doing x0=1 for each example

In [12]:
# delete names feature
X = np.delete(X, 0, axis=1)
X = X.astype(int)
# add x0 = 1
X = np.column_stack([np.ones((5,1), dtype=int), X])
# features normalization
X = (X - np.mean(X)) / np.std(X)
X

array([[-0.7804267 , -0.7804267 , -0.2549909 ,  1.35222448],
       [-0.7804267 , -0.81133469, -0.13135895,  1.90856826],
       [-0.7804267 , -0.81133469,  0.36316886,  2.00129223],
       [-0.7804267 , -0.7804267 , -0.16226694,  1.19768454],
       [-0.7804267 , -0.7804267 , -0.03863499,  1.63039637]])

In [13]:
'''
    assume that values at beginning
    there are a four theta for 4 features
    actually we don't need features normalization here
    because our cost function and gradient descent using h(x) as sigmoid function 
    which help us to get values between 0 and 1 but
    we need to handle decision boundary using the idea of probability
    that if h(x) >= .5 we will assign 1 for this examples and h(x) < .5 will assign 0
    
'''

thetas = np.array([
    [1],
    [1],
    [1],
    [1]
])
print("###########################################")
print(thetas.shape)
thetas

###########################################
(4, 1)


array([[1],
       [1],
       [1],
       [1]])

# Cost Function
    implemented using vectorized version
Now we should calculate the cost function that help us knowing what the cost error we have from prediction values and actual values.


<font color='green'> J(thetas) = (-1/m) * transpose(y)log(h(x)) + transpose(1-y)log(1-h(x)) </font>

<font color="green"> h(x) = g(z) & z = X*thetas</font>

<font color='green'> h(x) = g(z) = 1/(1 + exp(-z)) </font>

sometime we will handle that to be theta transpose and X because of will vectorize everything without loops


In [14]:
def costfunction(x, theats, y,m):
    '''
        this function will return the cost function as we explain above
        arguments
            x is the features of our training examples
            thetas that what we need to get at the end 
            which minimize our cost function with new examples            
            y is the actual value for each training example
            m the number of our training examples
        returned value
            the cost for the all training examples in J
    '''
    '''
    unvectorize version
    J(thetas) = (-1/m) * sum(ylog(h(x)) + (1-y)log(1-h(x)))
        let us implement each step for understanding
        h_x = np.dot(x, theats)
        below we get the difference between actual and predicted values
        cost_error = np.sum(y*log(h_x)+(1-y)*log(1-h_x))
        cost_error = (-1/m) * cost_error
    '''

    J = 0
    h_x = 1 / (1+ (np.exp(-(np.dot(X, thetas)))))
    part_1 = np.dot(y.T, np.log(h_x))
    part_2 = np.dot((1-y).T, (1 - np.log(h_x)))
    
    J = (-1/m) *  (part_1 + part_2)
    print("#############################################")
    print("divide cost_erro by 2*m \n",h_x)
    return abs(J)


In [15]:
cost_error = costfunction(X, thetas, y, X.shape[0])
print("#####################################")
print("cost error is \n", cost_error)

#############################################
divide cost_erro by 2*m 
 [[0.38612745]
 [0.54622957]
 [0.6841046 ]
 [0.37158204]
 [0.50772638]]
#####################################
cost error is 
 [[0.34637001]]


# Gradient Descent 
Now we should calculate thetas and reassigned it 
for new values with each iteration of gradient descent 
because we need the values of theta that minimize our cost function
we calculate above with each step of gradient decent we will calculate cost function to check if its actually minimized or not

vectorized version 

<font color='red'> thetas = thetas - (alpha/m) * transpose(X)*(g(X*thetas)-y) </font>

<font color='green'> h(x) = g(X*thetas) = 1/(1 + exp(-(X*thetas)) </font>
</font>


In [16]:
def gradientdescent(x,thetas,y,m,alpha):
#     predicted_actual = np.power(h_x-y,2)
#     mutiply_by_x = predicted_actual * x # here is a element wise multiplication
    '''
        we use vectorize version 
    '''
    '''
        unvectorized version
        thetas = thetas -(alpha/m) * sumation(((h(x) - y))*x)
    '''
    h_x = 1 / (1+ (np.exp(-(np.dot(X, thetas)))))
    thetas = thetas - (alpha/m) * np.dot(X.T, (h_x-y)) 
    
    return thetas
    
    

In [17]:
thetas = gradientdescent(X,thetas,y,X.shape[0],.09)
thetas

array([[0.99291674],
       [0.99248854],
       [0.99961293],
       [1.0189992 ]])

In [18]:
for i in range(100):
    '''
        we use vectorize version 
    '''
    thetas = gradientdescent(X, thetas, y, X.shape[0], .09)
    costs = costfunction(X,thetas,y,X.shape[0])
    print("###########################################")
    print("grad after\n", thetas)
    print("cost after\n",costs)

    

#############################################
divide cost_erro by 2*m 
 [[0.40314357]
 [0.56889555]
 [0.70424933]
 [0.38700691]
 [0.52800544]]
###########################################
grad after
 [[0.98653462]
 [0.98569071]
 [0.99925601]
 [1.03651032]]
cost after
 [[0.35296353]]
#############################################
divide cost_erro by 2*m 
 [[0.41067374]
 [0.57876008]
 [0.71285492]
 [0.3938315 ]
 [0.53687405]]
###########################################
grad after
 [[0.98079334]
 [0.97954505]
 [0.9989281 ]
 [1.05266333]]
cost after
 [[0.35570461]]
#############################################
divide cost_erro by 2*m 
 [[0.41761219]
 [0.58776035]
 [0.72062293]
 [0.40011887]
 [0.54498938]]
###########################################
grad after
 [[0.97563776]
 [0.97399537]
 [0.99862793]
 [1.06757677]]
cost after
 [[0.35814106]]
#############################################
divide cost_erro by 2*m 
 [[0.4240021 ]
 [0.59597463]
 [0.72764406]
 [0.40590807]
 [0.55241615]]
########

In [19]:
thetas


array([[1.03099963],
       [1.00075072],
       [0.99897759],
       [1.340815  ]])

In [20]:
test = np.array([
    [1, 1, 18, 70],
    [1, 4, 23,  76],
    [1,1, 25, 79]
])
test = (test - np.mean(test))/ np.std(test)
test

array([[-0.79573801, -0.79573801, -0.23209025,  1.49200876],
       [-0.79573801, -0.69627076, -0.0663115 ,  1.69094326],
       [-0.79573801, -0.79573801,  0.        ,  1.79041051]])

In [21]:
d = 1/(1+(np.exp(-(np.dot(thetas.T, test.T)))))
print(d)
d = (d>=.5)+0
print((d))

[[0.53790558 0.66458614 0.68651322]]
[[1 1 1]]
